name: Build and Publish Terraform Image contain Azure CLI and Mysql Client

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY_URL: docker.pkg.github.com
  CURRENT_DIR: ./terraform-azcli-mysql-ubuntu
  IMG_NAME: tf-az-mysql

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.CURRENT_DIR }}
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build --tag $REGISTRY_URL/${{ github.repository }}/$IMG_NAME:$GITHUB_RUN_ATTEMPT-$RUNNER_ARCH
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker push $REGISTRY_URL/${{ github.repository }}/$IMG_NAME:$GITHUB_RUN_ATTEMPT-$RUNNER_ARCH
